[package]
name = "client"
version = "0.1.0"
edition = "2021"
authors = ["Maxime LE HENAFF <maxime@lehenaff.pro", "Dora SAADAN <dorasaadan@gmail.com>", "Baptiste DEMARCHE <bdemarche@myges.fr>"]

[dependencies]
